### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by conradKE** [MillicentKinoti/Website-blocker#1]
would like to know how this works

**Comment by MillicentKinoti** [comment]
It's a simple python program runs in the background that blocks the
specified websites when you're working.

**Comment by conradKE** [comment]
wacha nione though me utumia shell sana

**Comment by MillicentKinoti** [comment]
Inarun kwa terminal pekee though...I'm working on the GUI

**Comment by conradKE** [comment]
Awesome  am following it looks interesting  
is there anyway i can reach you not through GH coz it doesn't support chats  maybe mail or handle

**Comment by MillicentKinoti** [comment]
On twitter @Camillekinoti

**Comment by conradKE** [comment]
awesome its been nice interacting with you

**Comment by MillicentKinoti** [comment]
Likewise
